### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by minaorangina** [ayooo-team/landing-page#1]
### React

- [x] ES6 / Babel transpiling
- [x] webpack config for production/development/testing?
- [x] .jshintrc
- [x] hot-loading
- [ ] ~~redux~~ not required here

### Sass

- [x] node-sass
- [x] sass loader

### Testing

- [x] Tape
- [x] React Test Utils
- [ ] ~~JSDom?~~ not required here

### Heroku

- [x] Account

### Database

- [ ] ~~ElasticSearch~~ not required here
- [ ] ~~S3~~ not required here

### Email

- [x] MailChimp and Mandrill

### Githooks
- [ ] ~~linting~~ decided against
- [x] run tests

**Comment by Danwhy** [comment]
Regarding testing, have you looked into [enzyme](https://github.com/airbnb/enzyme) as an alternative to React Test Utils? I've used it a little recently and found it much easier and more intuitive to use.  
Quick Intro: http://codeheaven.io/testing-react-components-with-enzyme/

**Comment by minaorangina** [comment]
@Danwhy I've heard of enzyme but never looked into it very much.  Thanks for the tip, we'll investigate!
