### ISSUE TITLE
Mailchimp

### ISSUE THREAD

**Issue by mk4111** [ayooo-team/landing-page#10]
- [x] embed mailchimp form
- [x] Paolo to make an account

**Comment by mk4111** [comment]
@PAOLOPRIAMODAMU Could you please create a new mailchimp account with your new ayooo email address?

**Comment by PAOLOPRIAMODAMU** [comment]
Done it.

Username: paolodamu
Password: PD1990dp?

Thanks

Paolo

On Friday, 18 March 2016, Marie <notifications@github.com> wrote:

> @PAOLOPRIAMODAMU <https://github.com/PAOLOPRIAMODAMU> Could you please
> create a new mailchimp account with your new ayooo email address?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ayooo-team/landing-page/issues/10#issuecomment-198474154>
>


-- 
Inviato da Gmail Mobile

**Comment by minaorangina** [comment]
@PAOLOPRIAMODAMU I've removed your mailchimp details from here, people might see it!

**Comment by minaorangina** [comment]
Pivoted to google forms.  Rest is completed, so closing
