### ISSUE TITLE
Sass and flexbox

### ISSUE THREAD

**Issue by mk4111** [ayooo-team/landing-page#11]
- [x] Mixins
- [x] media queries
- [x] meta tags
- [x] flexbox
- [x] *@*content

**Comment by minaorangina** [comment]
### *@*content
[Blog post on it here](http://krasimirtsonev.com/blog/article/SASS-content-directive-is-a-wonderful-thing)

Let's say you've defined a button mixin.
```
@mixin myButtonMixin {
    display: block;
    background-color: blue;
    text-decoration: none;
}
```

And you have various types of button. `.cancel` `.send` `.back`.  Each with slightly different style variations.

*@*content lets you **extend the mixin**.  
It's a placeholder for *n* number of extra css rules.

```
.cancel {
    @include myButtonMixin {
        background-color: red;
        font-weight: bold;
    }
}

.send {
    @include myButtonMixin {
        background-color: green;
        border: none;
    }
}
```

Tidier than passing in loads and loads of variables to your mixin.

**Comment by mk4111** [comment]
### *@*mixin & *@*placeholder
[Source:](http://www.sitepoint.com/sass-mixin-placeholder/)

In summary, both *@*mixin and *@*placeholder can be used to create reusable lines of CSS. They seem like CSS' version of (React's) reusable components in the sense that blocks of code can be referenced without having to repetitively type them out again and again. 

> There seem to be 2 big differences between *@*mixin and *@*placeholder: 

> [1] With a *@*mixin, you can pass variables - just as you might pass arguments in a function. A *@*placeholder lacks this sort of customisation. 

> [2] Although you're saved from having to go through the manual labour of repeating blocks of CSS with *@*mixin, when Sass compiles, it will do exactly that. So in effect, you end up with pretty much the same result: a bigger stylesheet. This is not the case with *@*placeholder. So, use *@*placeholder where possible.
