### ISSUE TITLE
Subscribing new users

### ISSUE THREAD

**Issue by minaorangina** [ayooo-team/landing-page#2]
- [x] ghost button
- [x] ~~ 'Thanks' popup modal~~ using google forms so no longer required
- [x] Google analytics - location of user on subscribing

**Comment by mk4111** [comment]
http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#create-post_lists_list_id_members

Older docs (mailchimp v1.3) say that on adding a new subscriber to the MailChimp list, MailChimp automatically sends a confirmation email. If this is no longer the case with v3.0, we could consider using the Mandrill API to send off emails as such.

**Comment by mk4111** [comment]
*Seems that the MailChimp list of subscribers is accessible through Mandrill's API :)
