### ISSUE TITLE
Desktop view: Replace Burger menu with full navigation links

### ISSUE THREAD

**Issue by mk4111** [ayooo-team/landing-page#41]
###### Comment number 5 from Client's email (dated 24/03/2016)
_"In the desktop version there should have not been the hamburger menu. We also agreed the first day that it would have looked like https://www.shyp.com/"_

**Comment by minaorangina** [comment]
Navigation links now visible in desktop view

**Comment by mk4111** [comment]
Hi @PAOLOPRIAMODAMU, if you are happy that this issue has now been solved, please could you click the 'Close Issue' button. Thank you!
