### ISSUE TITLE
#41 Menu do not disappeared after clicking on a section

### ISSUE THREAD

**Issue by PAOLOPRIAMODAMU** [ayooo-team/landing-page#51]
When I click on the hamburger menu we have a full screen menu with the different sections of "how it works"  "why ayooo" etc. 

There is a problem here: 

- When I click a section, like "why ayooo", the menu do not disappear

**Comment by mk4111** [comment]
Hi @PAOLOPRIAMODAMU , this should now be fixed! Please have a look and close to confirm that this is issue has been resolved. Thank you!

**Comment by iteles** [comment]
@mk4111 Worth using the labels and assignments for situations like this :wink:
